param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $repoRoot
$VenvPy = "$repoRoot\.venv\Scripts\python.exe"

if (-not (Test-Path $VenvPy)) {
    throw "Virtual environment interpreter not found at $VenvPy. Run install_dependencies.ps1 first."
}

function Invoke-Step {
    param(
        [string]$Name,
        [scriptblock]$Action
    )

    Write-Host "==> $Name" -ForegroundColor Cyan
    & $Action
}

function Invoke-CheckedCommand {
    param(
        [string]$Executable,
        [string[]]$Arguments
    )

    & $Executable @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $Executable $($Arguments -join ' ')"
    }
}

function Invoke-PoetryCommand {
    param([string[]]$Arguments)

    Invoke-CheckedCommand $VenvPy (@("-m", "poetry") + $Arguments)
}

function Ensure-Poetry {
    try {
        Invoke-PoetryCommand @("--version")
    }
    catch {
        Write-Host "Poetry was not found. Installing Poetry..." -ForegroundColor Yellow
        Invoke-CheckedCommand $VenvPy @("-m", "pip", "install", "poetry")
        Invoke-PoetryCommand @("--version")
    }
}

$pipelineFailed = $false
$failureMessage = $null

try {
    Invoke-Step "Install Poetry" {
        Ensure-Poetry
    }

    Invoke-Step "Install dev dependencies" {
        Invoke-PoetryCommand @("-v", "install", "--only", "dev", "--no-root")
    }

    Invoke-Step "Run Ruff" {
        Invoke-PoetryCommand @("run", "ruff", "check", ".")
    }

    Invoke-Step "Run Ruff format check" {
        Invoke-PoetryCommand @("run", "ruff", "format", "--check", ".")
    }

    Invoke-Step "Run Flake8" {
        Invoke-PoetryCommand @("run", "flake8", "modules", "auto_subtitle.py")
    }

    Invoke-Step "Run Pylint" {
        Invoke-PoetryCommand @("run", "pylint", "modules", "auto_subtitle.py")
    }

    Invoke-Step "Run tests with coverage" {
        Invoke-PoetryCommand @(
            "run",
            "pytest",
            "-o",
            "addopts=",
            "--cov=auto_subtitle",
            "--cov=modules",
            "--cov-branch",
            "--cov-report=xml",
            "--cov-report=json",
            "--cov-report=term",
            "--cov-fail-under=90",
            "tests/"
        )
    }

    Invoke-Step "Enforce per-file coverage >= 90%" {
        $coverageFiles = @(
            "auto_subtitle.py",
            "modules/config.py",
            "modules/isolated_translator.py",
            "modules/models.py",
            "modules/transcription.py",
            "modules/translation.py",
            "modules/utils.py"
        )

        foreach ($coverageFile in $coverageFiles) {
            Write-Host "   -> Checking $coverageFile" -ForegroundColor DarkCyan
            Invoke-PoetryCommand @(
                "run",
                "coverage",
                "report",
                "--include=$coverageFile",
                "--fail-under=90",
                "-m"
            )
        }
    }

}
catch {
    $pipelineFailed = $true
    $failureMessage = $_.Exception.Message
    Write-Host $failureMessage -ForegroundColor Red
}

try {
    Invoke-Step "Generate coverage badge and summary" {
        if ($pipelineFailed) {
            Write-Host "Skipping badge generation because a previous pipeline step failed." -ForegroundColor Yellow
            return
        }

        if (-not (Test-Path "coverage.xml")) {
            throw "coverage.xml was not generated by the test step."
        }

        Invoke-PoetryCommand @("run", "python", "tests/transform_metrics.py", "coverage.xml", "assets/coverage.svg")
    }
}
catch {
    $pipelineFailed = $true
    $failureMessage = $_.Exception.Message
    Write-Host $failureMessage -ForegroundColor Red
}

if ($pipelineFailed) {
    exit 1
}

Write-Host "Local pipeline completed successfully." -ForegroundColor Green