from typing import Any

class Separator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def load_model(self, *args: Any, **kwargs: Any) -> None: ...
    def separate(self, audio_input_path: str | list[str]) -> list[str]: ...
